service: aws-lambda-video-album
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  environment:
    DB_TABLE_NAME: 
    DB_URL: 
  iam:
    role:
      statements:
      - Effect: Allow
        Action:
          - dynamodb:*
        Resource: ${self:provider.environment.DB_URL}/${self:provider.environment.DB_TABLE_NAME}

functions:
  addVideo:
    handler: src/lambdas/add-video.addVideo
    events:
      - httpApi:
          path: /videos
          method: post
  getVideos:
    handler: src/lambdas/get-videos.getAllVideos
    events:
      - httpApi:
          path: /videos
          method: get
  getVideo:
    handler: src/lambdas/get-video.getVideoById
    events:
      - httpApi:
          path: /videos/{id}
          method: get
  deleteVideo:
    handler: src/lambdas/delete-video.deleteVideoById
    events:
      - httpApi:
          path: /videos/{id}
          method: delete

resources:
  Resources:
    VideosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DB_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1